### ISSUE TITLE
[BUG🪲] Missing `GetHostName()` method in `IGitURL` interface

### ISSUE THREAD

**Issue by anubhav06** [armosec/go-git-url#3]
# Problem
When implementing the example given in README of [parsing a git URL](https://github.com/kubescape/go-git-url#parse-a-git-url) we get this error: 
`gitURL.GetHostName undefined (type giturl.IGitURL has no field or method GetHostName)`  

![image](https://user-images.githubusercontent.com/43821031/206718778-2de31e78-7004-420a-9da6-9d3caaa07d92.png)

# Reason
The `GetHostName()` method is missing in the `IGitURL` interface present in [`interface.go`](https://github.com/kubescape/go-git-url/blob/master/interface.go#L10) file

# Solution
Simply adding the `GetHostName()` method to that `IGitURL` interface, fixes it

**Comment by anubhav06** [comment]
I was adding GitLab API support when I found the above bug

**Comment by dwertent** [comment]
Merged
